export enum TypeColors {
  grass = 'green',
  poison = 'purple',
  fire = 'red',
  flying = 'blue',
  water = 'cyan',
  bug = 'green',
  normal = 'gray',
  electric = 'yellow',
  ground = 'orange',
  fairy = 'pink',
  fighting = 'gray',
  psychic = 'red',
  rock = 'yellow',
  steel = 'gray',
  ice = 'blue.500',
  ghost = 'purple',
  dragon = 'oraange',
}
